export const data = {
  Laghouat: {
    Aflou: "Aflou - أفلو",
    "Aïn Madhi": "Ain Madhi - عين ماضي",
    "Aïn Sidi Ali": "Ain Sidi Ali - عين سهيه علي",
    Beidha: "Beidha - بيضاء",
    "Bennasser Benchohra": "Benacer Benchohra - بن ناصر بن شهرة",
    Brida: "Brida - بريدة",
    "El Assafia": "El Assafia - العسفية",
    "El Ghicha": "El Ghicha - الغيشة",
    "El Houaita": "El Haouaita - الحويطة",
    "Gueltat Sidi Saad": "Gueltat Sidi Saad - قتلة سيدي سعيد",
    "Hadj Mechri": "Hadj Mechri - الحاج مشري",
    "Hassi Delaa": "Hassi Delaa - حاسي الدلاعة",
    "Hassi R'Mel": "Hassi R'mel - حاسي الرمل",
    Kheneg: "Kheneg - الخنق",
    "Ksar El Hirane": "Ksar El Hirane - قصر الحيران",
    Laghouat: "Laghouat - الأغواط",
    "Oued M'Zi": "Oued M'zi - وادي مزي",
    "Oued Morra": "Oued Morra - وادي مرة",
    Sebgag: "Sebgag - سبقاق",
    "Sidi Bouzid": "Sidi Bouzid - سيدي بوزيد",
    "Sidi Makhlouf": "Sidi Makhlouf - سيدي مخلوف",
    Tadjemout: "Tadjemout - تاجموت",
    Tadjrouna: "Tadjrouna - تاجرونة",
    Taouiala: "Taouiala - تاويالة",
  },
  Chlef: {
    "Abou El Hassan": "Abou El Hassan - أبو الحسين",
    "Aïn Merane": "Ain Merane - عين مران",
    Bénairia: "Benairia - بنايرية",
    "Beni Bouateb": "Beni Bouattab - بني بوعتاب",
    "Beni Haoua": "Beni Haoua - بني حواء",
    "Beni Rached": "Beni Rached - بني راشد",
    Boukadir: "Boukadir - بوقادير",
    Bouzeghaia: "Bouzeghaia - بوزغاية",
    Breira: "Breira - بريرة",
    Chettia: "Chettia - الشطية",
    Chlef: "Chlef - الشلف",
    Dahra: "Dahra - الظهر",
    "El Hadjadj": "El Hadjadj - الحجاج",
    "El Karimia": "El Karimia - الكريمية",
    "El Marsa": "El Marsa - المرسى",
    Harchoun: "Harchoun - حرشون",
    Harenfa: "Herenfa - الهرنفة",
    "Labiod Medjadja": "Labiod Medjadja - الأبيض مجاجة",
    Moussadek: "Moussadek - مصدق",
    "Oued Fodda": "Oued Fodda - وادي الفضة",
    "Oued Goussine": "Oued Goussine - وادي قوسين",
    "Oued Sly": "Oued Sly - وادي سلي",
    "Ouled Abbes": "Ouled Abbes - أولاد عباس",
    "Ouled Ben Abdelkader": "Ouled Ben Abdelkader - أولاد بن عبد القادر",
    "Ouled Fares": "Ouled Fares - أولاد فارس",
    "Oum Drou": "Oum Drou - أم الدروع",
    Sendjas: "Sendjas - السنجاس",
    "Sidi Abderrahmane": "Sidi Abderrahmane - سيدي عبد الرحمن",
    "Sidi Akkacha": "Sidi Akkacha - سيدي عكاشة",
    Sobha: "Sobha - صبحة",
    Tadjena: "Tadjena - تاجنة",
    Talassa: "Talassa - تلعصة",
    Taougrite: "Taougrite - تاقريت",
    Ténès: "Tenes - تنس",
    Zeboudja: "Zeboudja - الزبوجة",
  },
  Béjaïa: {
    Adekar: "Adekar - أدكار",
    "Ait Djellil": "Beni Dejllil - بني جليل",
    "Aït Ksila": "Beni Ksila - بني كسيلة",
    "Aït Maouche": "Beni maouche - بني معوش",
    "Aït Mellikeche": "Beni-mallikeche - بني مليكش",
    "Aït R'zine": "Ait R'zine - أيت رزين",
    "Aït Smail": "Ait-smail - أيت إسماعيل",
    Akbou: "Akbou - أقبو",
    Akfadou: "Akfadou - أكفادو",
    Amalou: "Amalou - أمالو",
    Amizour: "Amizour - أميزور",
    Aokas: "Aokas - أوقاس",
    Barbacha: "Barbacha - برباشة",
    Béjaïa: "Bejaia - بجاية",
    Boudjellil: "Boudjellil - بو جليل",
    Bouhamza: "Bouhamza - بوحمزة",
    Boukhelifa: "Boukhelifa - بوخليفة",
    Chellata: "Chellata - شلاطة",
    Chemini: "Chemini - شميني",
    Darguina: "Darghina - درقينة",
    "Draâ El Kaïd": "Dra El Caid - ذراع القايد",
    "El Kseur": "El Kseur - القصر",
    "Fenaïa Ilmaten": "Fenaia Il Maten - فلاين الماثن",
    Ferraoun: "Feraoun - فرعون",
    "Ighil Ali": "Ighil-ali - إغيل علي",
    Ighram: "Ighram - إغرم",
    Kendira: "Kendira - كنديرة",
    Kherrata: "Kherrata - خراطة",
    Leflaye: "Leflaye - لفلاي",
    "M'cisna": "M'cisna - مسيسنة",
    Melbou: "Melbou - مالبو",
    "Oued Ghir": "Oued Ghir - وادي غير",
    Ouzellaguen: "Ouzellaguene - أوزلاقن",
    Seddouk: "Seddouk - صدوق",
    Semaoun: "Smaoun - سمعون",
    "Sidi Aïch": "Sidi-aich - سيدي عيش",
    "Sidi Ayad": "Sidi Ayad - سيدي عياد",
    "Souk El Ténine": "Souk El Tenine - سوق لإثنين",
    "Souk Oufella": "Souk Oufella - السوق أوفلا",
    "Tala Hamza": "Tala Hamza - تالة حمزة",
    Tamokra: "Tamokra - تامقرة",
    Tamridjet: "Tamridjet - تامريجت",
    "Taourirt Ighil": "Taourit Ighil - تاوريرت إغيل",
    Taskriout: "Taskriout - تاسكريوت",
    Tazmalt: "Tazmalt - تزمالت",
    Tibane: "Tibane - طيبان",
    Tichy: "Tichy - تيشي",
    Tifra: "Tifra - تيفرة",
    Timezrit: "Timezrit - تيمزريت",
    Tinabdher: "Tinebdar - تينبدار",
    "Tizi N'Berber": "Tizi-n'berber - تيزي نبربر",
    Toudja: "Toudja - توجة",
  },
  Bouira: {
    Aghbalou: "Aghbalou - أغبالو",
    "Ahl El Ksar": "Ahl El Ksar - أهل القصر",
    "Aïn Bessem": "Ain-bessem - عين بسام",
    "Aïn El Hadjar": "Ain El Hadjar - عين الحجر",
    "Aïn El Turc": "Ain Turk - عين الترك",
    "Aïn Laloui": "Ain Laloui - عين العلوي",
    "Aït Laziz": "Ait Laaziz - أيت لعزيز",
    Aomar: "Aomar - أعمر",
    "Ath Mansour": "Ath Mansour Taourirt - تاوريرت",
    Bechloul: "Bechloul - بشلول",
    "Bir Ghbalou": "Bir Ghbalou - بئر غبالو",
    "Bordj Okhriss": "Bordj Okhriss - برج أوخريص",
    Bouderbala: "Bouderbala - بودربالة",
    Bouira: "Bouira - البويرة",
    Boukram: "Boukram - بوكرم",
    Chorfa: "Chorfa - الشرفاء",
    Dechmia: "Dechmia - الدشمية",
    Dirrah: "Dirah - ديرة",
    Djebahia: "Djebahia - جباحية",
    "El Adjiba": "El Adjiba - العجيبة",
    "El Asnam": "El Asnam - الأسنام",
    "El Hachimia": "El Hachimia - الهاشمية",
    "El Hakimia": "El-hakimia - الحاكمية",
    "El Khabouzia": "El Khabouzia - الخبوزية",
    "El Mokrani": "El-mokrani - المقراني",
    Guerrouma: "Guerrouma - قرومة",
    "Hadjera Zerga": "Hadjera Zerga - الحجرة الزرقاء",
    Haizer: "Haizer - الحيزر",
    Hanif: "Hanif - حنيف",
    Kadiria: "Kadiria - القادرية",
    Lakhdaria: "Lakhdaria - الأخضرية",
    "M'Chedallah": "Mchedallah - مشد الله",
    Maala: "Maala - معلة",
    Maamora: "Maamora - المعمورة",
    Mezdour: "Mezdour - مزدور",
    "Oued El Berdi": "Oued El Berdi - وادي البردي",
    "Ouled Rached": "Ouled Rached - أولاد راشد",
    Raouraoua: "Raouraoua - روراوة",
    Ridane: "Ridane - ريدان",
    Saharidj: "Saharidj - الصهايج",
    "Souk El Khemis": "Souk El Khemis - سوق الخميس",
    "Sour El Ghouzlane": "Sour El Ghozlane - سور الغزلان",
    Taghzout: "Taghzout - تاغزوت",
    Taguedit: "Taguedite - تاقديت",
    Zbarbar: "Zbarbar - زبربر",
  },
  Tlemcen: {
    "Aïn Fetah": "Ain Fettah - عين فتاح",
    "Aïn Fezza": "Ain Fezza - عين فزة",
    "Aïn Ghoraba": "Ain Ghoraba - عين الغرابة",
    "Aïn Kebira": "Ain Kebira - العين الكبيرة",
    "Aïn Nehala": "Ain Nehala - عين نحالة",
    "Aïn Tallout": "Ain Tallout - عين تالوت",
    "Aïn Youcef": "Ain Youcef - عين يوسف",
    Amieur: "Amieur - عمير",
    Azails: "Azails - العزايل",
    "Bab El Assa": "Bab El Assa - باب العسة",
    "Beni Bahdel": "Beni Bahdel - بني بهدل",
    "Beni Boussaid": "Beni Boussaid - بني بوسعيد",
    "Beni Khellad": "Beni Khaled - بني راشد",
    "Beni Mester": "Beni Mester - بني مستر",
    "Beni Ouarsous": "Beni Ouarsous - بني وارسوس",
    "Beni Semiel": "Beni Smiel - بني صميل",
    "Beni Snous": "Beni Snous - بني سنوس",
    Bensekrane: "Bensekrane - إبن سكران",
    Bouhlou: "Bouhlou - بوحلو",
    Chetouane: "Chetouane - شتوان",
    "Dar Yaghmouracene": "Dar Yaghmouracene - دار يغمراسن",
    Djebala: "Djebala - جبالة",
    "El Aricha": "El Aricha - العريشة",
    "El Bouihi": "Bouihi - البويهي",
    "El Fehoul": "El Fehoul - الفحول",
    "El Gor": "El Gor - القور",
    Fellaoucene: "Fellaoucene - فلاوسن",
    Ghazaouet: "Ghazaouet - الغزوات",
    "Hammam Boughrara": "Hammam Boughrara - حمام بوغرارة",
    Hennaya: "Hennaya - الحناية",
    Honaïne: "Honaine - حنين",
    Maghnia: "Maghnia - مغنية",
    Mansourah: "Mansourah - منصورة",
    "Marsa Ben M'Hidi": "Marsa Ben M'hidi - مرسى بن مهيدي",
    "MSirda Fouaga": "Msirda Fouaga - مسيردة الفواقة",
    Nedroma: "Nedroma - ندرومة",
    "Oued Lakhdar": "oued lakhdar - واد لخضر",
    "Ouled Mimoun": "Ouled Mimoun - أولاد ميمون",
    "Ouled Riyah": "Ouled Riyah - أولاد رياح",
    Remchi: "Remchi - الرمشي",
    Sabra: "Sabra - صبرة",
    "Sebaa Chioukh": "Sebbaa Chioukh - السبعة شيوخ",
    Sebdou: "Sebdou - سبدو",
    "Sidi Abdelli": "Sidi Abdelli - سيدي عبد اللي",
    "Sidi Djillali": "Sidi Djilali - سيدي الجيلالي",
    "Sidi Medjahed": "Sidi Medjahed - سيدي مجاهد",
    Souahlia: "Souahlia - السواحلية",
    Souani: "Souani - السواني",
    "Souk Tlata": "Souk Tleta - سوق الثلاثاء",
    "Terny Beni Hdiel": "Terny Beni Hediel - تيرني بني هديل",
    Tienet: "Tianet - تيانت",
    Tlemcen: "Tlemcen - تلمسان",
    Zenata: "Zenata - زناتة",
  },
  Djelfa: {
    "Aïn Chouhada": "Ain Chouhada - عين الشهداء",
    "Aïn El Ibel": "Ain El Ibel - عين الإبل",
    "Aïn Feka": "Ain Fekka - عين فكة",
    "Aïn Maabed": "Ain Maabed - عين معبد",
    "Aïn Oussara": "Ain Oussera - عين وسارة",
    Amourah: "Amourah - عمورة",
    Benhar: "Benhar - بنهار",
    "Beni Yagoub": "Benyagoub - بني يعقوب",
    Birine: "Birine - بيرين",
    "Bouira Lahdab": "Bouira Lahdab - بويرة الأحدب",
    Charef: "Charef - الشارف",
    "Dar Chioukh": "Dar Chioukh - دار الشيوخ",
    Deldoul: "Deldoul - دلدول",
    Djelfa: "Djelfa - الجلفة",
    Douis: "Douis - دويس",
    "El Guedid": "El Guedid - القديد",
    "El Idrissia": "El Idrissia - الادريسية",
    "El Khemis": "El Khemis - الخميس",
    "Faidh El Botma": "Faidh El Botma - فيض البطمة",
    Guernini: "Guernini - قرنيني",
    Guettara: "Guettara - القطارة",
    "Had Sahary": "Had Sahary - حد الصحاري",
    "Hassi Bahbah": "Hassi Bahbah - حاسي بحبح",
    "Hassi El Euch": "Hassi El Euch - حاسي العش",
    "Hassi Fedoul": "Hassi Fedoul - حاسي فدول",
    "M'Liliha": "Mliliha - مليليحة",
    Messaad: "Messaad - مسعد",
    Moudjebara: "Moudjebara - مجبرة",
    "Oum Laadham": "Oum Laadham - أم العظام",
    "Sed Rahal": "Sed Rahal - سد الرحال",
    Selmana: "Selmana - سلمانة",
    "Sidi Baizid": "Sidi Baizid - سيدي بايزيد",
    "Sidi Ladjel": "Sidi Ladjel - سيدي لعجل",
    Tadmit: "Tadmit - تاعظميت",
    Zaafrane: "Zaafrane - زعفران",
    Zaccar: "Zaccar - زكار",
  },
};
